server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/control_panel
    username: root
    password: Sql@4321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true